In [1]:
import numpy as np
from scipy import stats


# Data sampel nilai dari 15 mahasiswa
data = [12, 25, 45, 67, 43, 33, 24, 45, 34, 11, 8, 34, 67, 99, 22]


# Melakukan Uji Kolmogorov-Smirnov
stat, p_value = stats.kstest(data, 'norm', args=(np.mean(data), np.std(data, ddof=1)))


print("Statistik Uji Kolmogorov-Smirnov:", stat)
print("p-value:", p_value)


# Menentukan apakah data berdistribusi normal atau tidak
alpha = 0.05
if p_value > alpha:
    print("Data berdistribusi normal (gagal menolak H0)")
else:
    print("Data tidak berdistribusi normal (menolak H0)")


Statistik Uji Kolmogorov-Smirnov: 0.18719291305040942
p-value: 0.604384295406073
Data berdistribusi normal (gagal menolak H0)


In [2]:
import numpy as np
from scipy.stats import chi2_contingency


# Data dari tabel
data = np.array([[14, 6, 9],
                 [10, 16, 10],
                 [2, 13, 20]])


# Menghitung chi-kuadrat
chi2, p, dof, expected = chi2_contingency(data)


# Menampilkan hasil
print(f"Chi-Square Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)


# Menentukan keputusan
alpha = 0.05
if p < alpha:
    print("Tolak H0: Ada hubungan antara pendapatan dan kualitas bahan makanan yang dikonsumsi")
else:
    print("Gagal Tolak H0: Tidak ada hubungan antara pendapatan dan kualitas bahan makanan yang dikonsumsi.")

Chi-Square Statistic: 18.366532937961512
P-value: 0.001046273329595159
Degrees of Freedom: 4
Expected Frequencies:
[[ 7.54 10.15 11.31]
 [ 9.36 12.6  14.04]
 [ 9.1  12.25 13.65]]
Tolak H0: Ada hubungan antara pendapatan dan kualitas bahan makanan yang dikonsumsi
